# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test2():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_2(self):
    self.driver.get("http://173.195.74.89:1880/ui/#!/1?socketid=6XskrxdGK7AiRMy6AADA")
    self.driver.set_window_size(1280, 680)
    self.driver.find_element(By.ID, "input_0").click()
    self.driver.find_element(By.ID, "input_0").send_keys("820134")
    self.driver.find_element(By.ID, "input_1").click()
    self.driver.find_element(By.ID, "input_1").send_keys("820134")
    self.driver.find_element(By.CSS_SELECTOR, ".md-container").click()
    self.driver.find_element(By.ID, "input_3").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".md-raised:nth-child(1)")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.ID, "input_3").send_keys("10")
    self.driver.find_element(By.CSS_SELECTOR, ".md-raised:nth-child(1)").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    WebDriverWait(self.driver, 5).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, ".md-toast-content")))
    value = self.driver.find_element(By.XPATH, "//h4[contains(.,\'Sent \"0A0908A6873252030A010A\"\')]").get_attribute("value")
    assert value == "Sent \"0A0908A6873252030A010A\""
